version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: internet-cwiczenia
    ports:
      - 8000:80
    volumes:
      - .:/srv/app
    #links:
      #- mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: db
      DB_USERNAME: db_user
      DB_PASSWORD: password
  mysql:
    image: mysql:8.0
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
