version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: internet-cwiczenia
    ports:
      - 8000:80
    volumes:
      - .:/srv/app
    #links:
      #- mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_docker
      DB_USERNAME: app
      DB_PASSWORD: password
  #mysql:
    #image: mysql:5.7
    #ports:
      #- 13306:3306
    #environment:
      #MYSQL_DATABASE: laravel_docker
      #MYSQL_USER: app
      #MYSQL_PASSWORD: password
      #MYSQL_ROOT_PASSWORD: password
